after-probe:
    find */jsconfig.json | xargs -d "\n" sed -i "s/\"checkJs\"\: false/\"checkJs\"\: true/"
    rg --files-with-matches --fixed-strings "let global: {};" ../.probe | xargs -d "\n" sed -i "s/let global\: {}\;/ /g"

codegen:
    @rm -rf ./server_scripts/common.gen/*
    @rm -rf ./client_scripts/common.gen/*
    @cp -r ./startup_scripts/common/* ./server_scripts/common.gen/
    @cp -r ./startup_scripts/common/* ./client_scripts/common.gen/

fmt:
    npx @biomejs/biome@2.5.5 format --write

check:
    npx typescript@7 -p ./server_scripts/jsconfig.json
    npx typescript@7 -p ./client_scripts/jsconfig.json
    npx typescript@7 -p ./startup_scripts/jsconfig.json