[configFiles]
	#File path to EnchantedEssence config file
	essenceConfigFilePath = "config/HBEnchantedEssenceConfig.json"

[performanceImpactConfig]
	#Dictates the performance impact of any Holy Buckets mods by controlling settings that influence operations per second or number of threads. Options are VERY_LOW, LOW, MEDIUM, HIGH, VERY_HIGH
	performanceImpact = "MEDIUM"
