[items]
	#List of tags to stack. Any tag in this list will stack with other entries in a tag. Note each item may only belong to 1 tag, may be unexpected results if it belongs to multiple.
	#Format is 'domain:name', for example 'c:ingots/'
	tags = ["kubejs:blueprint/gearbox", "kubejs:machinery/gearbox", "kubejs:blueprint/actuation", "kubejs:machinery/actuation", "kubejs:blueprint/chain_drive", "kubejs:machinery/chain_drive", "kubejs:shaft", "kubejs:belt"]
	#List of tag prefixes to stack. Any tag starting with the prefix will stack with other entries in the tag.
	#Format is 'domain:name', for example 'c:ingots/'
	prefixes = []
	#List of tags to ignore despite them matching one of the prefixes above.
	#Format is 'domain:name', for example 'c:ingots/special' if `c:ingots/` is a prefix
	prefix_blacklist = []
	#If true, when there is a remainder after transferring the stack, that remainder is converted to the target item.
	convert_remainder = false
